
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Difarifaldi
 */
public class LaporPage extends javax.swing.JFrame {

    /**
     * Creates new form LaporPage
     */
    public LaporPage(String Nama) {
        initComponents();
        snama.setText(Nama);
    }

    LaporPage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        JK1 = new javax.swing.JCheckBox();
        JD2 = new javax.swing.JCheckBox();
        JT2 = new javax.swing.JCheckBox();
        JB2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taTOTAL = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        JK2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        JL2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JD1 = new javax.swing.JCheckBox();
        JL1 = new javax.swing.JCheckBox();
        JT1 = new javax.swing.JCheckBox();
        JP2 = new javax.swing.JCheckBox();
        JBB = new javax.swing.JButton();
        Lapor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JP1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        snama = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Statuss = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB1.setText("Iya");

        JK1.setText("Iya");

        JD2.setText("Tidak");
        JD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JD2ActionPerformed(evt);
            }
        });

        JT2.setText("Tidak");
        JT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT2ActionPerformed(evt);
            }
        });

        JB2.setText("Tidak");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        taTOTAL.setColumns(20);
        taTOTAL.setForeground(new java.awt.Color(153, 153, 0));
        taTOTAL.setRows(5);
        jScrollPane1.setViewportView(taTOTAL);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Kelelahan");

        JK2.setText("Tidak");
        JK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JK2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Batuk-batuk");

        JL2.setText("Tidak");
        JL2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JL2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kesulitan bernafas");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Apakah suspect baru baru ini berpergian ke luar negeri?");

        JD1.setText("Iya");
        JD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JD1ActionPerformed(evt);
            }
        });

        JL1.setText("Iya");

        JT1.setText("Iya");

        JP2.setText("Tidak");
        JP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JP2ActionPerformed(evt);
            }
        });

        JBB.setText("Keluar");
        JBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBActionPerformed(evt);
            }
        });

        Lapor.setText("Lapor gejala");
        Lapor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Apakah suspect mengalami gejala-gejala berikut?");

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELF CEK PAGE");

        jLabel3.setFont(new java.awt.Font("Baron Neue", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VIXER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Demam");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tenggorokan kering / berdahak");

        JP1.setText("Iya");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Jika iya, ke negara mana suspect berkunjung?");

        jButton1.setText("Rujukan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Statuss.setColumns(20);
        Statuss.setRows(5);
        jScrollPane2.setViewportView(Statuss);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBB)
                        .addGap(111, 111, 111)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JP1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JP2))
                    .addComponent(jLabel1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL1)
                                .addGap(18, 18, 18)
                                .addComponent(JL2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JT1)
                                .addGap(18, 18, 18)
                                .addComponent(JT2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JD1)
                                .addGap(18, 18, 18)
                                .addComponent(JD2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB1)
                                .addGap(18, 18, 18)
                                .addComponent(JB2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JK1)
                                .addGap(18, 18, 18)
                                .addComponent(JK2))))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snama, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lapor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(snama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JD1)
                            .addComponent(JD2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JT1)
                            .addComponent(JT2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(JK1)
                            .addComponent(JK2))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(JB1)
                            .addComponent(JB2))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(JL2)
                            .addComponent(JL1))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JP1)
                            .addComponent(JP2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBB)
                    .addComponent(jButton1)
                    .addComponent(Lapor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JD2ActionPerformed

    private void JT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT2ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB2ActionPerformed

    private void JK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JK2ActionPerformed

    private void JL2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JL2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JL2ActionPerformed

    private void JD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JD1ActionPerformed

    }//GEN-LAST:event_JD1ActionPerformed

    private void JP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JP2ActionPerformed

    private void JBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBActionPerformed

      int response =JOptionPane.showConfirmDialog(this, "Apakah Ingin Keluar", "",JOptionPane.OK_CANCEL_OPTION ,JOptionPane.QUESTION_MESSAGE);
      if(response ==JOptionPane.OK_OPTION){
          JOptionPane.showMessageDialog(null," Terimaksih Anda telah Melapor Di aplikasi kami\"+\"\\n\"\n" +
"            + \" Laporan Anda akan kami kirim \"+\"\\n\"\n" +
"            + \" ke rumah sakit terdekat \"+\"\\n\";");
           System.exit(0);
        
}

    }//GEN-LAST:event_JBBActionPerformed

    private void LaporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporActionPerformed
        String lapor;
        lapor=" ";
        if(JD1.isSelected()){
            lapor += "1. istirahat yang cukup "
            +"\n "+"   dan periksalah ke dokter "+"\n";
        }
        else if(JD2.isSelected()){
            lapor += "1. Alhamdulillah anda tidak terkena demam "+"\n"
            + "   dan jangan lupa rajin berolahraga"+"\n";
        }
        if(JT1.isSelected()){
            lapor +="2. Anda harus banyak minum air putih "+"\n"
            + "   dan jangan lupa beristirahat"+"\n";
        }
        else if(JT2.isSelected()){
            lapor+="2. Anda harus tetap banyak minum air putih"+"\n";
        }
        if (JK1.isSelected()){
            lapor+="3. Anda harus banyak beristirahat"
            +"dan makan makanan bergizi"+"\n";
        }
        else if(JK2.isSelected()){
            lapor+="3. jagalah kondisi anda"
            +"   jangan sampai kelelahan"+"\n";
        }
        if(JB1.isSelected()){
            lapor+="4. Hindari makanan manis ,"+"\n"
            +"   Minumlah obat yang dianjurkan dokter"+"\n"
            +"   dan apabila batuk tutuplah dengan siku"+"\n";
        }
        else if(JB2.isSelected()){
            lapor+="4. Pakailah masker apabila keluar rumah"+"\n"
            +"   agar anda tidak tertular"+"\n";
        }
        if(JL1.isSelected()){
            lapor+="5. Segeralah cari pertolongan pertama"+"\n"
            +"   dan pergilah ke dokter "+"\n";
        }
        else if(JL2.isSelected()){
            lapor +="5. Olahraga yang rutin agar terhindar"+"\n"
            + "   dari sesak nafas"+"\n";
        }
        if(JP1.isSelected()){
            lapor +="Jika Anda pergi keluar negeri"+"\n"
            +"Periksalah diri anda ke rumah sakit terdekat"+"\n"
            ;
        }
        else if(JP2.isSelected()){
            lapor+="Tetaplah di rumah sampai batas waktu"+"\n"
            +"yang ditentukan agar tidak"+"\n"
            +"Tertular covid 19"+"\n";
        
        }

        taTOTAL.setText(lapor+"======================================"+"\n"
            +"Semoga anda sehat-sehat saja"+"\n"
            +"Dan terhindar dari virus corona");
       
    }//GEN-LAST:event_LaporActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        RMH tampildata = new RMH(); 
                     setVisible(true);
                     tampildata.setVisible(true);
                      this.dispose();
                     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String lapor;
        lapor = " ";
        if(JB1.isSelected()){
            if(JT1.isSelected())
                if(JK1.isSelected())
                    if(JD1.isSelected())
                        if(JL1.isSelected())
                        Statuss.setText(lapor+" Anda Kemungkinan Besar Positif Corona");
              
              } 
 if(JB1.isSelected()){
            if(JT2.isSelected())
                if(JK2.isSelected())
                    if(JD2.isSelected())
                        if(JL2.isSelected())
                        Statuss.setText(lapor+" Anda Hanya Batuk"); 
    }//GEN-LAST:event_jButton2ActionPerformed
        
     if(JB1.isSelected()){
            if(JT1.isSelected())
                if(JK1.isSelected())
                    if(JD2.isSelected())
                        if(JL2.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Dalam Pengawasan");
    }
      if(JB1.isSelected()){
            if(JT1.isSelected())
                if(JK1.isSelected())
                    if(JD1.isSelected())
                        if(JL2.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Dalam Pengawasan");
    }
     if(JB2.isSelected()){
            if(JT1.isSelected())
                if(JK1.isSelected())
                    if(JD1.isSelected())
                        if(JL1.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Dalam Pengawasan");
    }
      if(JB1.isSelected()){
            if(JT2.isSelected())
                if(JK1.isSelected())
                    if(JD1.isSelected())
                        if(JL1.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Dalam Pengawasan");
    }
       if(JB1.isSelected()){
            if(JT1.isSelected())
                if(JK2.isSelected())
                    if(JD1.isSelected())
                        if(JL1.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Dalam Pengawasan");
    }
        if(JB1.isSelected()){
            if(JT1.isSelected())
                if(JK1.isSelected())
                    if(JD2.isSelected())
                        if(JL1.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Dalam Pengawasan");
    }
        if(JB2.isSelected()){
            if(JT2.isSelected())
                if(JK2.isSelected())
                    if(JD1.isSelected())
                        if(JL2.isSelected())
                           
                        
            Statuss.setText(lapor+" Anda Hanya Demam");
    
    }
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JB1;
    private javax.swing.JCheckBox JB2;
    private javax.swing.JButton JBB;
    private javax.swing.JCheckBox JD1;
    private javax.swing.JCheckBox JD2;
    private javax.swing.JCheckBox JK1;
    private javax.swing.JCheckBox JK2;
    private javax.swing.JCheckBox JL1;
    private javax.swing.JCheckBox JL2;
    private javax.swing.JCheckBox JP1;
    private javax.swing.JCheckBox JP2;
    private javax.swing.JCheckBox JT1;
    private javax.swing.JCheckBox JT2;
    private javax.swing.JButton Lapor;
    private javax.swing.JTextArea Statuss;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField snama;
    private javax.swing.JTextArea taTOTAL;
    // End of variables declaration//GEN-END:variables
}
