
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Difarifaldi
 */
public class RMH extends javax.swing.JFrame {

    /**
     * Creates new form RMH
     */
    public RMH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Kota = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        BBB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PPQ = new javax.swing.JTextArea();
        QQ = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Kota Anda");

        jLabel3.setText("Rumah Sakit Terdekat");

        Kota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Pilih Kota)", "Jakarta Barat", "Jakarta Timur", "Bogor", "Jakarta Pusat", "Tangsel", "Depok", "Jakarta Selatan", " " }));
        Kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KotaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 230, 64));
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BBB.setBackground(new java.awt.Color(249, 38, 19));
        BBB.setText("Kembali");
        BBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBBActionPerformed(evt);
            }
        });

        PPQ.setColumns(20);
        PPQ.setRows(5);
        jScrollPane1.setViewportView(PPQ);

        QQ.setText("Cek");
        QQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QQActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(52, 152, 219));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Rumah Sakit Rujukan Yang Terdekat");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("VIXER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BBB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(QQ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BBB)
                            .addComponent(QQ)
                            .addComponent(jButton1)))
                    .addComponent(jLabel3))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KotaActionPerformed

    }//GEN-LAST:event_KotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String kota = Kota.getSelectedItem().toString();
        String lapor;
        lapor=" ";
        if(kota=="(Pilih Kota)"){
            JOptionPane.showMessageDialog(null,"Anda Belum Memlilih kota",
                "",JOptionPane.ERROR_MESSAGE);
        }
        if(kota=="Jakarta Barat"){
            PPQ.setText(lapor+"RS Medika Permata"+"\n"+"RS Royal Taruma"
                +"\n"+"RS Hermina Daan Mogot");
        }
        if(kota=="Jakarta Timur"){
            PPQ.setText(lapor+"RSUD Pasar Rebo"+"\n"+"RS Islam Pondok Kopi"
                +"\n"+"RS Harun Sisma");
        }
        if(kota=="Jakarta Pusat"){
            PPQ.setText(lapor+"RS HUSADA"+"\n"+"RS Islam Jakarta"
                +"\n"+"RS YPK Mandiri");
        }
        if(kota=="Jakarta Selatan"){
            PPQ.setText(lapor+"RS Fatmawati"+"\n"+"RS Pondok Indah"
                +"\n"+"RS Ibu dan Anak");
        }
        if(kota=="Depok"){
            PPQ.setText(lapor+"RS HGA"+"\n"+"RS Naura Medika"
                +"\n"+"RS Hermina");
        }
        if(kota=="Bogor"){
            PPQ.setText(lapor+"RSUD Cibinong"+"\n"+"RS Azra"
                +"\n"+"RS Bogor Medical Center");
        }
        if(kota=="Tangsel"){
            PPQ.setText(lapor+"RSUD Tangsel"+"\n"+"RS Medika BSD"
                +"\n"+"RS Asih Ciputat");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBBActionPerformed

        int response =JOptionPane.showConfirmDialog(this, "Apakah Ingin Keluar", "sss",JOptionPane.OK_CANCEL_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if(response ==JOptionPane.OK_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_BBBActionPerformed

    private void QQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QQActionPerformed
        String kota = Kota.getSelectedItem().toString();
        String lapor;
        lapor=" ";
        if("Depok".equals(kota)){
            Depok cgf = new Depok();
            cgf.setVisible(true);
            cgf.pack();
            cgf.setLocationRelativeTo(null);
            cgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        if("Jakarta Barat".equals(kota)){
            Jakbar sgf = new Jakbar();
            sgf.setVisible(true);
            sgf.pack();
            sgf.setLocationRelativeTo(null);
            sgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        if("Jakarta Timur".equals(kota)){
            Jaktim agf = new Jaktim();
            agf.setVisible(true);
            agf.pack();
            agf.setLocationRelativeTo(null);
            agf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        if("Jakarta Pusat".equals(kota)){
            Jakpus rgf = new Jakpus();
            rgf.setVisible(true);
            rgf.pack();
            rgf.setLocationRelativeTo(null);
            rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        } if("Jakarta Selatan".equals(kota)){
            Jaksel egf = new Jaksel();
            egf.setVisible(true);
            egf.pack();
            egf.setLocationRelativeTo(null);
            egf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        if("Bogor".equals(kota)){
            Bogor wgf = new Bogor();
            wgf.setVisible(true);
            wgf.pack();
            wgf.setLocationRelativeTo(null);
            wgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
        if("Tangsel".equals(kota)){
            Tangsel qgf = new Tangsel();
            qgf.setVisible(true);
            qgf.pack();
            qgf.setLocationRelativeTo(null);
            qgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }

    }//GEN-LAST:event_QQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RMH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBB;
    private javax.swing.JComboBox Kota;
    private javax.swing.JTextArea PPQ;
    private javax.swing.JButton QQ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
